- name: Create a directory if it does not exist
  file:
    path: /opt/services/traefik
    state: directory
    mode: '0755'

- name: Copy traefik docker compose and env file
  template:
    src: "{{ item }}"
    dest: /opt/services/traefik
  loop: 
    - ./templates/traefik/docker-compose.yml
    - ./templates/traefik/.env

- name: Create web_net docker network for traefik service
  community.docker.docker_network: 
    name: web_net
    driver: bridge
    driver_options:
      com.docker.network.bridge.name: web_net
    state: present

- name: Create app_net docker network 
  community.docker.docker_network: 
    name: app_net
    driver: bridge
    driver_options:
      com.docker.network.bridge.name: app_net
    state: present

# - name: pull traefik docker image
#   shell: docker compose -f /opt/services/traefik/docker-compose.yml pull

# - name: create traefik docker container 
#   shell: docker compose -f /opt/services/traefik/docker-compose.yml up -d
