apiVersion: v1
kind: PersistentVolume
metadata:
  name: main-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt"
