apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt"
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simple-app-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
spec:
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - image: ahmadrafiee/mecan-sample-app:ver1
        name: simple-app
        ports:
        - containerPort: 80
        volumeMounts:
        - name: simple-app-persistent-storage
          mountPath: /opt
      volumes:
      - name: simple-app-persistent-storage
        persistentVolumeClaim:
          claimName: simple-app-pvc
