server:
  extraArgs:
    - --insecure

  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt 
      certmanager.k8s.io/acme-http01-edit-in-place: "false"
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    enabled: true
    hosts:
      - argo.kube.cloudflow.ir
    ingressClassName: nginx
    https: true
    tls:
      - secretName: argocd-general-tls
        hosts:
          - argo.kube.cloudflow.ir
