version: '3.8'

networks:
  web_net:
    external: true

services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    networks:
      - web_net
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web_net"
      - "traefik.http.routers.kubernetes-dashboard.entrypoints=http"
      - "traefik.http.routers.kubernetes-dashboard.rule=Host(`${KUBE_SUB}.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.kubernetes-dashboard.middlewares=https-redirect"
      - "traefik.http.routers.kubernetes-dashboard-secure.entrypoints=https"
      - "traefik.http.routers.kubernetes-dashboard-secure.rule=Host(`${KUBE_SUB}.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.kubernetes-dashboard-secure.tls=true"
      - "traefik.http.routers.kubernetes-dashboard-secure.tls.options=default"
      - "traefik.http.routers.kubernetes-dashboard-secure.tls.certresolver=mycert"
      - "traefik.http.routers.kubernetes-dashboard-secure.service=kubernetes-dashboard"
      - "traefik.http.services.kubernetes-dashboard.loadbalancer.server.port=8080"
      
      - "traefik.http.routers.haproxy.entrypoints=http"
      - "traefik.http.routers.haproxy.rule=Host(`${HAPROXY_SUB}.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.haproxy.middlewares=https-redirect"
      - "traefik.http.routers.haproxy-secure.entrypoints=https"
      - "traefik.http.routers.haproxy-secure.rule=Host(`${HAPROXY_SUB}.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.haproxy-secure.tls=true"
      - "traefik.http.routers.haproxy-secure.tls.options=default"
      - "traefik.http.routers.haproxy-secure.tls.certresolver=mycert"
      - "traefik.http.routers.haproxy-secure.service=haproxy"
      - "traefik.http.services.haproxy.loadbalancer.server.port=8404"

      - "traefik.http.routers.ingress.entrypoints=http"
      - "traefik.http.routers.ingress.rule=Host(`${INGRESS}.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.ingress.middlewares=https-redirect"
      - "traefik.http.routers.ingress-secure.entrypoints=https"
      - "traefik.http.routers.ingress-secure.rule=Host(`${INGRESS}.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.ingress-secure.tls=true"
      - "traefik.http.routers.ingress-secure.tls.options=default"
      - "traefik.http.routers.ingress-secure.tls.certresolver=mycert"
      - "traefik.http.routers.ingress-secure.service=ingress"
      - "traefik.http.services.ingress.loadbalancer.server.port=8090"

