apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: ClusterIP
  selector:                         # Add this section
    app: web       # This label should match the label in your deployment's pod template
  ports:
    - port: 7070
      protocol: TCP
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  annotations:
    kubernetes.io/change-cause: ver1
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: web      # This label should match the label in your service's selector
  replicas: 5
  template: 
    metadata:
      labels:
        app: web # This label should match the label in your service's selector
        svc: example
    spec:
      containers:
        - name: web-application
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              memory: 20Mi
              cpu: 20m
