apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
    - image: busybox
      command:  
        - sleep
        - "1800"
      imagePullPolicy: IfNotPresent
      name: busybox
      volumeMounts:
        - mountPath: /etc/kubernetes
          name: k8setcdcert
  hostNetwork: true
  nodeName: master1
  volumes:
    - hostPath:
        path: /etc/kubernetes
        type: ""
      name: k8setcdcert
  restartPolicy: Always
