apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudflow-app-ds
  labels:
    app: cloudflow-test-ds
  annotations:
    cloudflow.ir/change-cause: ver1
spec:
  selector:
    matchLabels:
      app: cloudflow-test-ds
  template:
    metadata:
      labels:
        app: cloudflow-test-ds
        svc: example
    spec:
      containers:
        - name: cloudflow-app
          image: ahmadrafiee/mecan-sample-app:ver1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              memory: 20Mi
              cpu: 20m
