apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  type: ClusterIP
  selector:                         # Add this section
    app: hello-world-deploy         # This label should match the label in your deployment's pod template
  ports:
    - port: 7070
      protocol: TCP
      targetPort: 80