---
- hosts: haproxy-server
  become: true
  vars:
    ansible_ssh_private_key_file: /Users/siavashmohseni/.ssh/id_rsa
  gather_facts: yes
  name: Install and config haproxy for kubernetes cluster 
  roles:
    - { role: roles/haproxy, become: True}

